FROM node:24-alpine3.23@sha256:2bdb65ed1dab192432bc31c95f94155ca5ad7fc1392fb7eb7526ab682fa5bf14

RUN corepack enable && corepack prepare pnpm@10.24.0 --activate

WORKDIR /usr/src/app

USER node

CMD ["sh", "/usr/src/app/scripts/run-migrations.sh"]
